numbers = input().split(" ")
print(int(numbers[0])+int(numbers[1]))
print(int(numbers[0])-int(numbers[1]))
print(int(numbers[0])*int(numbers[1]))
print(int(numbers[0])//int(numbers[1]))
print(int(numbers[0])%int(numbers[1]))